---
# defaults file for proxmox_deploy
VM_template: mantic-server-cloudimg-amd64
default_disk: virtio0
default_interface: ens18
default_volume: /dev/vda
default_partition: 2
template_name: template-debian-deployment